spcs83.exe : spcs83.o \
batgp.o \
batpc.o \
claim.o \
drgppc.o \
drpcgp.o \
formgp.o \
formpc.o \
gppc83.o \
hdgp.o \
hdpc.o \
intgp.o \
intpc.o \
lamd1.o \
lamr1.o \
$(OBJ1)lstftn.o \
lconst.o \
oconst.o \
pcgp83.o \
skewd.o \
skewr.o \
tblspc.o \
tconpc.o \
tconst.o \
tmgeod.o \
tmgrid.o \
todms.o \
verdms.o
	fort77 -o spcs83.exe \
	spcs83.o \
	batgp.o \
	batpc.o \
	claim.o \
	drgppc.o \
	drpcgp.o \
	formgp.o \
	formpc.o \
	gppc83.o \
	hdgp.o \
	hdpc.o \
	intgp.o \
	intpc.o \
	lamd1.o \
	lamr1.o \
	$(OBJ1)lstftn.o \
	lconst.o \
	oconst.o \
	pcgp83.o \
	skewd.o \
	skewr.o \
	tblspc.o \
	tconpc.o \
	tconst.o \
	tmgeod.o \
	tmgrid.o \
	todms.o \
	verdms.o
spcs83.o : spcs83.for
	fort77 -c spcs83.for -o spcs83.o
batgp.o :batgp.for 
	fort77 -c batgp.for -o batgp.o
batpc.o :batpc.for 
	fort77 -c batpc.for -o batpc.o
claim.o :claim.for 
	fort77 -c claim.for -o claim.o
drgppc.o :drgppc.for 
	fort77 -c drgppc.for -o drgppc.o
drpcgp.o :drpcgp.for 
	fort77 -c drpcgp.for -o drpcgp.o
formgp.o :formgp.for 
	fort77 -c formgp.for -o formgp.o
formpc.o :formpc.for 
	fort77 -c formpc.for -o formpc.o
gppc83.o :gppc83.for 
	fort77 -c gppc83.for -o gppc83.o
hdgp.o :hdgp.for 
	fort77 -c hdgp.for -o hdgp.o
hdpc.o :hdpc.for 
	fort77 -c hdpc.for -o hdpc.o
intgp.o :intgp.for 
	fort77 -c intgp.for -o intgp.o
intpc.o :intpc.for 
	fort77 -c intpc.for -o intpc.o
lamd1.o :lamd1.for 
	fort77 -c lamd1.for -o lamd1.o
lamr1.o :lamr1.for 
	fort77 -c lamr1.for -o lamr1.o
$(OBJ1)lstftn.o :$(SRC1)lstftn.for 
	fort77 -c $(SRC1)lstftn.for -o $(OBJ1)lstftn.o
lconst.o :lconst.for 
	fort77 -c lconst.for -o lconst.o
oconst.o :oconst.for 
	fort77 -c oconst.for -o oconst.o
pcgp83.o :pcgp83.for 
	fort77 -c pcgp83.for -o pcgp83.o
skewd.o :skewd.for 
	fort77 -c skewd.for -o skewd.o
skewr.o :skewr.for 
	fort77 -c skewr.for -o skewr.o
tblspc.o :tblspc.for 
	fort77 -c tblspc.for -o tblspc.o
tconpc.o :tconpc.for 
	fort77 -c tconpc.for -o tconpc.o
tconst.o :tconst.for 
	fort77 -c tconst.for -o tconst.o
tmgeod.o :tmgeod.for 
	fort77 -c tmgeod.for -o tmgeod.o
tmgrid.o :tmgrid.for 
	fort77 -c tmgrid.for -o tmgrid.o
todms.o :todms.for 
	fort77 -c todms.for -o todms.o
verdms.o :verdms.for 
	fort77 -c verdms.for -o verdms.o
